services:
  web:
    depends_on:
      - server
    build: ./frontend
    ports:
      - "3000:3000"
    command: npm start
    networks:
      - bridged-network
    develop:
      watch:
        - path: ./frontend/src
          target: /app/src
          action: sync
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild


  server:
    depends_on:
      - db
    build: ./backend
    ports:
      - "3001:3000"
    command: npm run dev
    networks:
      - bridged-network
    develop:
      watch:
        - path: ./backend
          target: /app
          action: sync
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
    environment:
      PGHOST: db
      PGPORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db


  db:
    build: ./database
    ports:
      - "5432:5432"
    networks:
      - bridged-network
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    networks:
      - bridged-network
    environment:
      PGADMIN_DEFAULT_EMAIL: email@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    

volumes:
  db-data:
  pgadmin-data:

networks:
  bridged-network:
    driver: bridge